from turtle import color
import matplotlib.pyplot as plt
import numpy as np
x=np.arange(0,10*np.pi,0.0001)
def f(x,e):
    a=(1-(e**2))
    return a/(1+(e*np.cos((1-(3/a))*x)))
fig, axs = plt.subplots(2,5,figsize=(15,6))
fig.suptitle('Orbitas con diferentes excentricidades')
axs[0, 0].plot(f(x,0.0)*np.cos(x), f(x,0.0)*np.sin(x),'tab:blue',linewidth=0.7)
axs[0, 0].scatter(0,0,s=5,color='black')
axs[0, 0].set_title('e=0')
axs[0, 0].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[0, 0].minorticks_on()
axs[0, 0].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[0, 1].plot(f(x,0.1)*np.cos(x), f(x,0.1)*np.sin(x), 'tab:orange',linewidth=0.7)
axs[0, 1].scatter(0,0,s=5,color='black')
axs[0, 1].set_title('e=0.1')
axs[0, 1].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[0, 1].minorticks_on()
axs[0, 1].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[0, 2].plot(f(x,0.2)*np.cos(x), f(x,0.2)*np.sin(x), 'tab:green',linewidth=0.7)
axs[0, 2].scatter(0,0,s=5,color='black')
axs[0, 2].set_title('e=0.2')
axs[0, 2].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[0, 2].minorticks_on()
axs[0, 2].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[0, 3].plot(f(x,0.3)*np.cos(x), f(x,0.3)*np.sin(x), 'tab:red',linewidth=0.7)
axs[0, 3].scatter(0,0,s=5,color='black')
axs[0, 3].set_title('e=0.3')
axs[0, 3].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[0, 3].minorticks_on()
axs[0, 3].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[0, 4].plot(f(x,0.4)*np.cos(x), f(x,0.4)*np.sin(x), 'tab:purple',linewidth=0.7)
axs[0, 4].scatter(0,0,s=5,color='black')
axs[0, 4].set_title('e=0.4')
axs[0, 4].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[0, 4].minorticks_on()
axs[0, 4].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[1, 0].plot(f(x,0.5)*np.cos(x), f(x,0.5)*np.sin(x), 'tab:brown',linewidth=0.7)
axs[1, 0].scatter(0,0,s=5,color='black')
axs[1, 0].set_title('e=0.5')
axs[1, 0].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[1, 0].minorticks_on()
axs[1, 0].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[1, 1].plot(f(x,0.6)*np.cos(x), f(x,0.6)*np.sin(x), 'tab:pink',linewidth=0.7)
axs[1, 1].scatter(0,0,s=5,color='black')
axs[1, 1].set_title('e=0.6')
axs[1, 1].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[1, 1].minorticks_on()
axs[1, 1].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[1, 2].plot(f(x,0.7)*np.cos(x), f(x,0.7)*np.sin(x), 'tab:red',linewidth=0.7)
axs[1, 2].scatter(0,0,s=5,color='black')
axs[1, 2].set_title('e=0.7')
axs[1, 2].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[1, 2].minorticks_on()
axs[1, 2].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[1, 3].plot(f(x,0.8)*np.cos(x), f(x,0.8)*np.sin(x), 'tab:gray',linewidth=0.7)
axs[1, 3].scatter(0,0,s=5,color='black')
axs[1, 3].set_title('e=0.8')
axs[1, 3].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[1, 3].minorticks_on()
axs[1, 3].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[1, 4].plot(f(x,0.9)*np.cos(x), f(x,0.9)*np.sin(x), 'tab:olive',linewidth=0.7)
axs[1, 4].scatter(0,0,s=5,color='black')
axs[1, 4].set_title('e=0.9')
axs[1, 4].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[1, 4].minorticks_on()
axs[1, 4].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
for ax in axs.flat:
    ax.set(xlabel='Eje x', ylabel='Eje y')

for ax in axs.flat:
    ax.label_outer()
plt.savefig("Solucion1.1.png",dpi=500)
#----------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------
y=np.arange(0,6*np.pi,0.0001)
fig, axs = plt.subplots(2,5,figsize=(15,6))
fig.suptitle('Orbitas con diferentes excentricidades')
axs[0, 0].plot(f(y,1.1)*np.cos(y), f(y,1.1)*np.sin(y),'tab:blue',linewidth=0.7)
axs[0, 0].scatter(0,0,s=5,color='black')
axs[0, 0].set_title('e=1.1')
axs[0, 0].set_xlim([-2, 2])
axs[0, 0].set_ylim([-2, 2])
axs[0, 0].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[0, 0].minorticks_on()
axs[0, 0].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[0, 1].plot(f(y,1.2)*np.cos(y), f(y,1.2)*np.sin(y), 'tab:orange',linewidth=0.7)
axs[0, 1].scatter(0,0,s=5,color='black')
axs[0, 1].set_title('e=1.2')
axs[0, 1].set_xlim([-2, 2])
axs[0, 1].set_ylim([-2, 2])
axs[0, 1].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[0, 1].minorticks_on()
axs[0, 1].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[0, 2].plot(f(y,1.3)*np.cos(y), f(y,1.3)*np.sin(y), 'tab:green',linewidth=0.7)
axs[0, 2].scatter(0,0,s=5,color='black')
axs[0, 2].set_title('e=1.3')
axs[0, 2].set_xlim([-2, 2])
axs[0, 2].set_ylim([-2, 2])
axs[0, 2].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[0, 2].minorticks_on()
axs[0, 2].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[0, 3].plot(f(y,1.4)*np.cos(y), f(y,1.4)*np.sin(y), 'tab:red',linewidth=0.7)
axs[0, 3].scatter(0,0,s=5,color='black')
axs[0, 3].set_title('e=1.4')
axs[0, 3].set_xlim([-2, 2])
axs[0, 3].set_ylim([-2, 2])
axs[0, 3].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[0, 3].minorticks_on()
axs[0, 3].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[0, 4].plot(f(y,1.5)*np.cos(y), f(y,1.5)*np.sin(y), 'tab:purple',linewidth=0.7)
axs[0, 4].scatter(0,0,s=5,color='black')
axs[0, 4].set_title('e=1.5')
axs[0, 4].set_xlim([-2, 2])
axs[0, 4].set_ylim([-2, 2])
axs[0, 4].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[0, 4].minorticks_on()
axs[0, 4].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[1, 0].plot(f(y,1.6)*np.cos(y), f(y,1.6)*np.sin(y), 'tab:brown',linewidth=0.7)
axs[1, 0].scatter(0,0,s=5,color='black')
axs[1, 0].set_title('e=1.6')
axs[1, 0].set_xlim([-2, 2])
axs[1, 0].set_ylim([-2, 2])
axs[1, 0].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[1, 0].minorticks_on()
axs[1, 0].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[1, 1].plot(f(y,1.7)*np.cos(y), f(y,1.7)*np.sin(y), 'tab:pink',linewidth=0.7)
axs[1, 1].scatter(0,0,s=5,color='black')
axs[1, 1].set_title('e=1.7')
axs[1, 1].set_xlim([-2, 2])
axs[1, 1].set_ylim([-2, 2])
axs[1, 1].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[1, 1].minorticks_on()
axs[1, 1].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[1, 2].plot(f(y,1.8)*np.cos(y), f(y,1.8)*np.sin(y), 'tab:red',linewidth=0.7)
axs[1, 2].scatter(0,0,s=5,color='black')
axs[1, 2].set_title('e=1.8')
axs[1, 2].set_xlim([-2, 2])
axs[1, 2].set_ylim([-2, 2])
axs[1, 2].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[1, 2].minorticks_on()
axs[1, 2].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[1, 3].plot(f(y,1.9)*np.cos(y), f(y,1.9)*np.sin(y), 'tab:gray',linewidth=0.7)
axs[1, 3].scatter(0,0,s=5,color='black')
axs[1, 3].set_title('e=1.9')
axs[1, 3].set_xlim([-2, 2])
axs[1, 3].set_ylim([-2, 2])
axs[1, 3].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[1, 3].minorticks_on()
axs[1, 3].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
axs[1, 4].plot(f(y,2)*np.cos(y), f(y,2)*np.sin(y), 'tab:olive',linewidth=0.7)
axs[1, 4].scatter(0,0,s=5,color='black')
axs[1, 4].set_title('e=2')
axs[1, 4].set_xlim([-2, 2])
axs[1, 4].set_ylim([-2, 2])
axs[1, 4].grid(b=True, which='major', color=(0,0,0), linestyle='-')
axs[1, 4].minorticks_on()
axs[1, 4].grid(b=True, which='minor', color=(0.2,0.2,0.2), linestyle='-', alpha=0.2)
for ax in axs.flat:
    ax.set(xlabel='Eje x', ylabel='Eje y')

for ax in axs.flat:
    ax.label_outer()
plt.savefig("Solucion1.2.png",dpi=500)
plt.show()
